### ISSUE TITLE
Doesn't works

### ISSUE THREAD

**Issue by Animyos** [hexian000/NativeProcess#1]
I've downloaded the newest APK from the GitHub page and installed the application. When I start the app, it shows no tasks or processes, even though there are definitely some apps running. Here is a screenshot: ![Screenshot_20210511-104140.png](https://user-images.githubusercontent.com/82672160/117786432-c7d45100-b245-11eb-8679-c188f525b10a.png)
My system information:

Operating system: Android 10
Device: HMD Global Nokia 3.4

I'm going to try the app on a device with Android 5 too.

Or do I need root access?

**Comment by Animyos** [comment]
Ok, an update: I can't install it on Android 5.1, it says "Parsing error".

**Comment by hexian000** [comment]
Yes, you will need root access to run this app like the README said.

**Comment by Animyos** [comment]
Ok. Then I can close this issue.
